# Generated by Django 5.2.6 on 2025-10-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sportsmatch_delete_sports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsmatch',
            options={},
        ),
        migrations.AlterField(
            model_name='sportsmatch',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportsmatch',
            name='image',
            field=models.ImageField(default='sports/default_match.jpg', upload_to='sports/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sportsmatch',
            name='slug',
            field=models.SlugField(blank=True, default='null', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('stand', models.CharField(max_length=100)),
                ('ring', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_booked', models.BooleanField(default=False)),
                ('extra_meta', models.JSONField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='sports.sportsmatch')),
            ],
            options={
                'unique_together': {('match', 'code')},
            },
        ),
    ]
