# Generated by Django 5.2.7 on 2025-10-28 14:52

import django.db.models.deletion
import sports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booked_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bays',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.bay'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(default=sports.models.generate_booking_ref, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='entry_gate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
